### ISSUE TITLE
add-nsx-t-routers job: weird error message

### ISSUE THREAD

**Issue by guillierf** [sparameswaran/nsx-t-gen#10]
weird error message (because the ESXi was successfully prep'ed and added as TN):

TASK [Check for Fabric Node Status failed] *************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
skipping: [localhost] => (item={u'body': u"{links : None, ip_addresses : ['10.173.62.41'], create_user : admin, create_time : 1526930680017, last_modified_time : 1526930680017, discovered_ip_addresses : [], id : e64416ea-b02b-4b40-af57-740a97e27aee, display_name : ESXi-1.mylab.com, last_modified_user : admin, schema : None, description : None, tags : None, self_ : None, protection : NOT_PROTECTED, system_owned : None, fqdn : , revision : 0, external_id : e64416ea-b02b-4b40-af57-740a97e27aee, resource_type : HostNode}", '_ansible_parsed': True, 'attempts': 1, '_ansible_item_result': True, '_ansible_no_log': False, u'ansible_job_id': u'806783813815.811', 'failed': False, u'changed': True, u'object_name': u'ESXi-1.mylab.com', 'item': {'_ansible_parsed': True, '_ansible_item_result': True, '_ansible_no_log': False, u'ansible_job_id': u'806783813815.811', 'item': u'ESXi-1.mylab.com', u'started': 1, 'changed': True, 'failed': False, u'finished': 0, u'results_file': u'/root/.ansible_async/806783813815.811', '_ansible_ignore_errors': None}, u'finished': 1, u'invocation': {u'module_args': {u'display_name': u'ESXi-1.mylab.com', u'nsx_manager': u'10.173.62.44', u'node_username': u'root', u'nsx_passwd': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'nsx_username': u'admin', u'os_version': u'6.5.0', u'state': u'present', u'thumbprint': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER', u'os_type': u'ESXI', u'ip_address': u'10.173.62.41', u'node_passwd': u'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER'}}, u'id': u'e64416ea-b02b-4b40-af57-740a97e27aee', '_ansible_ignore_errors': True}) 

for info, the whole job ran successfully

**Comment by sparameswaran** [comment]
It just checks for errors (and ignores errors that are complaining of duplicate node or hosts already having been added).
