### ISSUE TITLE
SNAT rules on T0: we need to be able to specify destination IP

### ISSUE THREAD

**Issue by guillierf** [sparameswaran/nsx-t-gen#11]
for now, the SNAT rule in the param file looks like this:

# Sample entry for PKS PKS-Infra network
  - t0_router: DefaultT0Router
    nat_type: snat
    source_network: 10.1.1.0/24      # PKS Infra network cidr
    translated_network: 23.23.23.1       # SNAT External Address for PKS networks
    rule_priority: 8001                  # Lower priority

SNAT is dangerous when the destination network is too wide (i.e destination IP = ANY).

for PKS, we usually restrict the destination IP to a specific CIDR (we don't use ANY because it can break internal communications, from T1 to T1). 

request is to be able to specify destination IP (or destination_network) in the above NAT section

**Comment by sparameswaran** [comment]
added destination_network as optional param for snat rule set.
