### ISSUE TITLE
How to create T1-Routers and Connect to T0

### ISSUE THREAD

**Issue by LightInTheDarknet** [sparameswaran/nsx-t-gen#14]
Hi,

we are struggeling to find the Ansible-Tasks which create the T1-Routers. In the video [(blogpost)](https://allthingsmdw.blogspot.com/2018/05/introducing-nsx-t-gen-automating-nsx-t.html) there are Tasks shown (Create T1, Create Downlinks), but we cannot see this in the repository.

Please advise us how to go forward. Usecase is that we have existing T0-Routers and try to generate T1+x.

**Comment by sparameswaran** [comment]
The ansible code resides in a different repo: https://github.com/sparameswaran/nsxt-ansible
The t1 router creation is handled within configure_nsx_routers.yml playbook. Best to invoke from configureNsx.yml as it requires some other configs (like edge cluster id). Let me know if you need any additional details/help.

**Comment by LightInTheDarknet** [comment]
Ok, i see the Problem.   
We looked at "configure_nsx.yml" (which does not include T1), but you use "configureNsx.yml", which is a different File and includes the first one. The naming is... :sweat_smile: 

Thanks!

**Comment by sparameswaran** [comment]
Would be interested in your feedback and usefulness of the tool. Thanks.
