### ISSUE TITLE
OVAs not being deployed

### ISSUE THREAD

**Issue by garreeoke** [sparameswaran/nsx-t-gen#15]
When running the install-nsx-t job get the following output from log (Noting happens in vsphere):
TASK [deploy NSX Manager] ******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [localhost] => (item=nsx-manager)

TASK [Wait 4 minutes before starting to verify the deployment] *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Pausing for 240 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [localhost]

TASK [Check if NSX Managers deployment has finished] ***************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
failed: [localhost] (item={'_ansible_parsed': True, '_ansible_item_result': True, '_ansible_no_log': False, u'ansible_job_id': u'608769329668.1235', 'failed': False, u'started': 1, 'changed': True, 'item': u'nsx-manager', u'finished': 0, u'results_file': u'/root/.ansible_async/608769329668.1235', '_ansible_ignore_errors': None}) => {"ansible_job_id": "608769329668.1235", "attempts": 1, "changed": false, "cmd": "/root/.ansible/tmp/ansible-tmp-1529068294.9-145461286954642/deploy_ova.py", "data": "", "finished": 1, "item": {"ansible_job_id": "608769329668.1235", "changed": true, "failed": false, "finished": 0, "item": "nsx-manager", "results_file": "/root/.ansible_async/608769329668.1235", "started": 1}, "msg": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1529068294.9-145461286954642/async_wrapper.py\", line 150, in _run_module\n    (filtered_outdata, json_warnings) = _filter_non_json_lines(outdata)\n  File \"/root/.ansible/tmp/ansible-tmp-1529068294.9-145461286954642/async_wrapper.py\", line 91, in _filter_non_json_lines\n    raise ValueError('No start of json char found')\nValueError: No start of json char found\n", "stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_NMDIln/ansible_module_deploy_ova.py\", line 164, in <module>\n    main()\n  File \"/tmp/ansible_NMDIln/ansible_module_deploy_ova.py\", line 146, in main\n    if resource_pool is not None and resource_pool != '':\nNameError: global name 'resource_pool' is not defined\n", "stderr_lines": ["Traceback (most recent call last):", "  File \"/tmp/ansible_NMDIln/ansible_module_deploy_ova.py\", line 164, in <module>", "    main()", "  File \"/tmp/ansible_NMDIln/ansible_module_deploy_ova.py\", line 146, in main", "    if resource_pool is not None and resource_pool != '':", "NameError: global name 'resource_pool' is not defined"]}
	to retry, use: --limit @/tmp/build/6fab756d/nsxt-ansible/deploy_mgr.retry

**Comment by sparameswaran** [comment]
Sorry for the outage, just pushed changes.

**Comment by sparameswaran** [comment]
fixed.
