### ISSUE TITLE
Need to add the ability to use multiple clusters

### ISSUE THREAD

**Issue by NiranEC77** [sparameswaran/nsx-t-gen#16]
1. When there are multi AZ you need multiple clusters prepared
2. When opsmanager and bosh are on the management cluster
Sometimes the additional clusters may have different uplink profiles so need to add the ability to connect them to their respective profiles.
Least priority is for multiple Compute vCenters

**Comment by sparameswaran** [comment]
multiple vcenter compute clusters supported.
