### ISSUE TITLE
Allow custom names for nsx-mgr and controllers

### ISSUE THREAD

**Issue by sparameswaran** [sparameswaran/nsx-t-gen#5]
Name of nsx-mgr and nsx-controller appear to be hardcoded. Allow overriding of the default names.

**Comment by guillierf** [comment]
I tried these attributes in the nsx-t-params.yml:

nsx_t_manager_fqdn: nsx-t-mgr.mylab.com
nsx_t_manager_host_name: 'concourse-nsx-t-mgr' # Without spaces*
nsx_t_manager_vm_name: 'concourse-NSX-T-manager'
nsx_t_manager_ip: 10.173.13.3
nsx_t_manager_admin_user: admin
nsx_t_manager_admin_pwd: VMware1!         # Min 8 chars, upper, lower, number, special digit
nsx_t_manager_root_pwd: VMware1!          # Min 8 chars, upper, lower, number, special digit


but once the OVA is deployed in vCenter, the VM cannot be started.
error message displayed on vCenter:
"Property 'Hostname' must be configured for the VM to power on"


log output from the job:
TASK [Check if NSX Managers deployment has finished] ***************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /tmp/build/6fab756d/nsxt-ansible/deploy_ovas.yml:100
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/utilities/logic/async_status.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1525709898.86-147688904847378 `" && echo ansible-tmp-1525709898.86-147688904847378="` echo /root/.ansible/tmp/ansible-tmp-1525709898.86-147688904847378 `" ) && sleep 0'
<localhost> PUT /root/.ansible/tmp/ansible-local-1042xXYc3F/tmp7E3h4U TO /root/.ansible/tmp/ansible-tmp-1525709898.86-147688904847378/async_status.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1525709898.86-147688904847378/ /root/.ansible/tmp/ansible-tmp-1525709898.86-147688904847378/async_status.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1525709898.86-147688904847378/async_status.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1525709898.86-147688904847378/ > /dev/null 2>&1 && sleep 0'
failed: [localhost] (item={'_ansible_parsed': True, '_ansible_item_result': True, '_ansible_no_log': False, u'ansible_job_id': u'899216887645.1066', 'failed': False, u'started': 1, 'changed': True, 'item': u'nsx-manager', u'finished': 0, u'results_file': u'/root/.ansible_async/899216887645.1066', '_ansible_ignore_errors': None}) => {
    "ansible_job_id": "899216887645.1066", 
    "attempts": 1, 
    "changed": false, 
    "finished": 1, 
    "invocation": {
        "module_args": {
            "admin_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "allow_ssh_root_login": "True", 
            "cli_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "cluster": "CONCOURSE-MGMT-cluster", 
            "datacenter": "Datacenter2", 
            "datastore": "datastore20", 
            "deployment_size": "medium", 
            "disk_mode": "thin", 
            "dns_domain": "mylab.com", 
            "dns_server": "10.20.20.1", 
            "gateway": "10.173.13.125", 
            "hostname": "", 
            "ip_address": "10.173.13.3", 
            "netmask": "255.255.255.128", 
            "ntp_server": "10.113.60.176", 
            "ova_file": "nsx-unified-appliance-2.1.0.0.0.7395503.ova", 
            "ovftool_path": "/usr/bin", 
            "path_to_ova": "/root/ISOs/CHGA", 
            "portgroup": "MGMT-PG-1525", 
            "portgroup_ext": null, 
            "portgroup_transport": null, 
            "ssh_enabled": "True", 
            "vcenter": "10.173.62.220", 
            "vcenter_passwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "vcenter_user": "administrator@vsphere.local", 
            "vmname": "concourse-NSX-T-manager"
        }
    }, 
    "item": {
        "ansible_job_id": "899216887645.1066", 
        "changed": true, 
        "failed": false, 
        "finished": 0, 
        "item": "nsx-manager", 
        "results_file": "/root/.ansible_async/899216887645.1066", 
        "started": 1
    }, 
    "msg": "Failed to deploy OVA, error message from ovftool is: Opening OVA source: /root/ISOs/CHGA/nsx-unified-appliance-2.1.0.0.0.7395503.ova\nThe manifest does not validate\nOpening VI target: vi://administrator%40vsphere.local@10.173.62.220:443/Datacenter2/host/CONCOURSE-MGMT-cluster/\nDeploying to VI: vi://administrator%40vsphere.local@10.173.62.220:443/Datacenter2/host/CONCOURSE-MGMT-cluster/\n\rDisk progress: 1%\rDisk progress: 2%\rDisk progress: 3%\rDisk progress: 4%\rDisk progress: 5%\rDisk progress: 6%\rDisk progress: 7%\rDisk progress: 8%\rDisk progress: 9%\rDisk progress: 10%\rDisk progress: 11%\rDisk progress: 12%\rDisk progress: 13%\rDisk progress: 14%\rDisk progress: 15%\rDisk progress: 16%\rDisk progress: 17%\rDisk progress: 18%\rDisk progress: 19%\rDisk progress: 20%\rDisk progress: 21%\rDisk progress: 22%\rDisk progress: 23%\rDisk progress: 24%\rDisk progress: 25%\rDisk progress: 26%\rDisk progress: 27%\rDisk progress: 28%\rDisk progress: 29%\rDisk progress: 30%\rDisk progress: 31%\rDisk progress: 32%\rDisk progress: 33%\rDisk progress: 34%\rDisk progress: 35%\rDisk progress: 36%\rDisk progress: 37%\rDisk progress: 38%\rDisk progress: 39%\rDisk progress: 40%\rDisk progress: 41%\rDisk progress: 42%\rDisk progress: 43%\rDisk progress: 44%\rDisk progress: 45%\rDisk progress: 46%\rDisk progress: 47%\rDisk progress: 48%\rDisk progress: 49%\rDisk progress: 50%\rDisk progress: 51%\rDisk progress: 52%\rDisk progress: 53%\rDisk progress: 54%\rDisk progress: 55%\rDisk progress: 56%\rDisk progress: 57%\rDisk progress: 58%\rDisk progress: 59%\rDisk progress: 60%\rDisk progress: 61%\rDisk progress: 62%\rDisk progress: 63%\rDisk progress: 64%\rDisk progress: 65%\rDisk progress: 66%\rDisk progress: 67%\rDisk progress: 68%\rDisk progress: 69%\rDisk progress: 70%\rDisk progress: 71%\rDisk progress: 72%\rDisk progress: 73%\rDisk progress: 74%\rDisk progress: 75%\rDisk progress: 76%\rDisk progress: 77%\rDisk progress: 78%\rDisk progress: 79%\rDisk progress: 80%\rDisk progress: 81%\rDisk progress: 82%\rDisk progress: 83%\rDisk progress: 84%\rDisk progress: 85%\rDisk progress: 86%\rDisk progress: 87%\rDisk progress: 88%\rDisk progress: 89%\rDisk progress: 90%\rDisk progress: 91%\rDisk progress: 92%\rDisk progress: 93%\rDisk progress: 94%\rDisk progress: 95%\rDisk progress: 96%\rDisk progress: 97%\rDisk progress: 98%\rDisk progress: 99%\rTransfer Completed                    \nPowering on VM: concourse-NSX-T-manager\n\rTask progress: 5%\rTask Failed                           \nError: Task failed on server: Property 'Hostname' must be configured for the VM to power on.\nError: Reached maximum wait time of 5 minutes when aborting.\nCompleted with errors\n, the comand was ['/usr/bin/ovftool', '--acceptAllEulas', '--skipManifestCheck', '--X:injectOvfEnv', '--powerOn', '--noSSLVerify', '--allowExtraConfig', '--diskMode=thin', '--datastore=datastore20', '--name=concourse-NSX-T-manager', '--deploymentOption=medium', '--network=MGMT-PG-1525', '--prop:nsx_hostname=', '--prop:nsx_dns1_0=10.20.20.1', '--prop:nsx_domain_0=mylab.com', '--prop:nsx_ntp_0=10.113.60.176', '--prop:nsx_gateway_0=10.173.13.125', '--prop:nsx_ip_0=10.173.13.3', '--prop:nsx_netmask_0=255.255.255.128', '--prop:nsx_passwd_0=********', '--prop:nsx_cli_passwd_0=********', '--prop:nsx_isSSHEnabled=True', '--prop:nsx_allowSSHRootLogin=True', '/root/ISOs/CHGA/nsx-unified-appliance-2.1.0.0.0.7395503.ova', 'vi://administrator@vsphere.local:********@10.173.62.220/Datacenter2/host/CONCOURSE-MGMT-cluster/']"
}
	to retry, use: --limit @/tmp/build/6fab756d/nsxt-ansible/deploy_ovas.retry

PLAY RECAP *********************************

**Comment by sparameswaran** [comment]
Did your pipeline get synced up? can you do a `fly -t <target> get-pipeline -p <pipeline-name>` and see if it lists *NSX_T_MANAGER_HOST_NAME* in the list of parameters passed to the pipeline?

**Comment by guillierf** [comment]
indeed,

I don't see it.

I only see:
$ fly -t local get-pipeline -p install-nsx-t
NSX_T_MANAGER_ADMIN_PWD: VMware1!
      NSX_T_MANAGER_ADMIN_USER: admin
      NSX_T_MANAGER_FQDN: nsx-t-mgr.mylab.com
      NSX_T_MANAGER_IP: 10.173.13.3
      NSX_T_MANAGER_ROOT_PWD: VMware1!
      NSX_T_MANAGER_VM_NAME: concourse-NSX-T-manager
      NSX_T_MGR_DEPLOY_SIZE: medium


How can I sync the pipeline?
everytime I make a change in the param file, I delete the previous pipeline and create a new one.

**Comment by sparameswaran** [comment]
You just have to do a `git pull` of the repo. Use the same params file as you have already edited while doing set-pipeline against the refreshed pipelines/nsx-t-install.yml

**Comment by guillierf** [comment]
ah ok.
I didn't know the repo was updated. 
Will test and keep you updated

**Comment by guillierf** [comment]
yes it worked!
