### ISSUE TITLE
ESXi host not appearing as TN

### ISSUE THREAD

**Issue by guillierf** [sparameswaran/nsx-t-gen#7]
nsx-t-params.yml:

<SNIP>

esxi_hosts_root_pwd: VMware1!  # EDIT - Root password for the esxi hosts
esxi_hosts_config: |
  esxi_hosts:
  - name: esxi-host1.mylab.com
    ip: 10.173.13.2
    root_pwd: VMware1!
nsx_t_esxi_vmnics: vmnic1 # vmnic1,vmnic2...
<SNIP>

after the install-nsx-t job, I don't see the ESXi host (10.173.13.2) as Transport Node.
However, I can see the ESXi host Fabric -> Nodes -> Hosts.

**Comment by sparameswaran** [comment]
Do you still see the issue? did the esxi host get added as transport nodes? can you rerun the add-routers job?

**Comment by guillierf** [comment]
it worked the second time I launched the add-nsx-routers job.
I think the root cause is the following:
the step that configures the ESXi as TN comes too fast.
There should be a timer (or a longer timer) between the step where the ESXi is added as Fabric Host (in this step, VIB are installed on the ESXi and it can take some time) and the step where the ESXi is configured as TN.

**Comment by sparameswaran** [comment]
Added wait between addition as Fabric host and TN.

**Comment by garreeoke** [comment]
This pipeline was working for me yesterday, now it does not work.  I will paste error

**Comment by garreeoke** [comment]
failed: [localhost] (item={'_ansible_parsed': True, '_ansible_item_result': True, '_ansible_no_log': False, u'ansible_job_id': u'608769329668.1235', 'failed': False, u'started': 1, 'changed': True, 'item': u'nsx-manager', u'finished': 0, u'results_file': u'/root/.ansible_async/608769329668.1235', '_ansible_ignore_errors': None}) => {"ansible_job_id": "608769329668.1235", "attempts": 1, "changed": false, "cmd": "/root/.ansible/tmp/ansible-tmp-1529068294.9-145461286954642/deploy_ova.py", "data": "", "finished": 1, "item": {"ansible_job_id": "608769329668.1235", "changed": true, "failed": false, "finished": 0, "item": "nsx-manager", "results_file": "/root/.ansible_async/608769329668.1235", "started": 1}, "msg": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1529068294.9-145461286954642/async_wrapper.py\", line 150, in _run_module\n    (filtered_outdata, json_warnings) = _filter_non_json_lines(outdata)\n  File \"/root/.ansible/tmp/ansible-tmp-1529068294.9-145461286954642/async_wrapper.py\", line 91, in _filter_non_json_lines\n    raise ValueError('No start of json char found')\nValueError: No start of json char found\n", "stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_NMDIln/ansible_module_deploy_ova.py\", line 164, in <module>\n    main()\n  File \"/tmp/ansible_NMDIln/ansible_module_deploy_ova.py\", line 146, in main\n    if resource_pool is not None and resource_pool != '':\nNameError: global name 'resource_pool' is not defined\n", "stderr_lines": ["Traceback (most recent call last):", "  File \"/tmp/ansible_NMDIln/ansible_module_deploy_ova.py\", line 164, in <module>", "    main()", "  File \"/tmp/ansible_NMDIln/ansible_module_deploy_ova.py\", line 146, in main", "    if resource_pool is not None and resource_pool != '':", "NameError: global name 'resource_pool' is not defined"]}
	to retry, use: --limit @/tmp/build/6fab756d/nsxt-ansible/deploy_mgr.retry

**Comment by garreeoke** [comment]
Sorry will open new issue

**Comment by sparameswaran** [comment]
Sorry for the outage, just pushed changes. Was adding support to specify different clusters and resource pool for each controller, ending up breaking things.

**Comment by garreeoke** [comment]
Thanks!  I just tried and seems to be working!  I love this pipeline, thx!

**Comment by garreeoke** [comment]
One question for you.  I work for VMware and I'm trying to use this for PKS
setup with help from Francis.  Currently, with the pipeline, my K8 worker
nodes are on a 10.2.2.1 network and being Nat'd to 23.23.23.1.  In this
scenario, the worker nodes do not have access to the internet.  Are there
any rules that can be put in place to make this happen in the pipeline?
I'm not a networking person, sorry for the question.

-Aaron

**Comment by sparameswaran** [comment]
check canned-pks for deploying in offline envs.
