### ISSUE TITLE
add tag for TZ (overlay)

### ISSUE THREAD

**Issue by guillierf** [sparameswaran/nsx-t-gen#8]
in the param file, we cannot specify tags for TZ (the overlay one)

this is needed for PKS

**Comment by guillierf** [comment]
This is all the tags we need for PKS:

T0 Router:  {'ncp/shared_resource'  :  true}
Overlay Transport Zone: {'ncp/shared_resource'  :  true}
NAT IP Block: {'ncp/shared_resource'  :  true}
Floating/External IP Pool - {'ncp/shared_resource'  :  true} and {'ncp/external' : true}


in the sample param files, I notices some default tags are not correctly set

**Comment by sparameswaran** [comment]
Added support for tags in the sample params as mentioned.
